DELETE TABLE IF EXISTS REACTION;

DELETE TABLE IF EXISTS COMMENT;

DELETE TABLE IF EXISTS THREAD_COLLABOLATOR;

DELETE TABLE IF EXISTS THREAD;

DELETE TABLE IF EXISTS ACCOUNT;

DROP EXTENSION IF EXISTS citext;